fix: reporting workflow

diff --git a/.github/workflows/system-tests.yml b/.github/workflows/system-tests.yml
--- a/.github/workflows/system-tests.yml
+++ b/.github/workflows/system-tests.yml
@@ -46,13 +46,12 @@ jobs:
       - name: Run tests
         run: npm run test --workspace=network-tests
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
+      - name: Upload test report
+        uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
         with:
-          name: Jest test # Name of the check run which will be created
-          path: network-tests/jest-*.xml # Path to test results
-          reporter: jest-junit
+          name: test-results
+          path: network-tests/jest-report.xml
 
       - name: Cleanup
         run: |
